---

  - name: Install apache
    apt: name=apache2

  - name: Enable apache modules
    apache2_module: name={{ item }}
    with_items:
      - proxy
      - proxy_http
      - rewrite

  - name: Configure apache proxy
    template: src=proxy.conf.j2 dest=/etc/apache2/conf-available/proxy.conf

  - name: Configure apache ports
    template: src=ports.conf.j2 dest=/etc/apache2/ports.conf

  - name: Enable apache service
    service: name=apache2 state=started enabled=yes

  - name: Enable proxy configuration
    command: a2enconf proxy
    notify: restart apache2
