---

  - name: Install apache
    apt: name=apache2

  - name: Enable apache modules
    apache2_module: name={{ item }}
    with_items:
      - proxy
      - proxy_http
      - proxy_wstunnel
      - rewrite
      - ssl

  - name: Create ssl directory
    file: path=/etc/apache2/ssl state=directory

  - name: Install ssl certificate
    template: src=apache.crt.j2 dest=/etc/apache2/ssl/apache.crt
  
  - name: Install ssl private key
    template: src=apache.key.j2 dest=/etc/apache2/ssl/apache.key

  - name: Configure apache proxy
    template: src=proxy.conf.j2 dest=/etc/apache2/conf-available/proxy.conf

  - name: Configure apache ports
    template: src=ports.conf.j2 dest=/etc/apache2/ports.conf

  - name: Enable apache service
    service: name=apache2 state=started enabled=yes

  - name: Enable proxy configuration
    command: a2enconf proxy
    notify: restart apache2
