---

- hosts: rana
  roles:
    - common
    - postfix
    - apache
    - mongodb
    - node
    - { role: rana, tags: ["rana"] }
    - { role: backup, tags: ["backup"] }
  vars_files:
    - secure.yml
  sudo: yes
