---

  - name: Sync rana code
    git:
      repo: git@github.com:ecohealthalliance/rana.git
      dest: "{{ rana_prefix }}"
      accept_hostkey: yes
      version: "{{rana_branch}}"
    register: rana_sync
    sudo_user: "{{ rana_user }}"

  - name: Remove untracked files in rana repo directory
    shell: "git clean -dfx"
    args:
      chdir: "{{ rana_prefix }}"
    when: rana_sync.changed
    sudo: yes

  - name: Remove meteor
    file: path=/usr/local/bin/meteor state=absent
    when: rana_sync.changed

  - name: Install meteor
    shell: curl https://install.meteor.com | /bin/sh chdir=/tmp creates=/usr/local/bin/meteor
    sudo: yes
    when: rana_sync.changed

  - name: Create config
    template: src=meteor_config.j2 dest={{ rana_prefix }}/config mode=0755
    when: rana_sync.changed
    sudo_user: "{{ rana_user }}"

  - pip: virtualenv="{{ rana_prefix }}/.venv" requirements="{{ rana_prefix }}/.scripts/requirements.txt"
    when: rana_sync.changed

  - name: Import data from dbpedia
    command: "{{ rana_prefix }}/.venv/bin/python import_dbpedia_data.py --mongo_url {{meteor_mongo}} --db_name {{meteor_db_name}}"
    args:
      chdir: "{{ rana_prefix }}/.scripts"
    when: rana_sync.changed
    sudo_user: "{{ rana_user }}"

  - name: meteor bundle
    command: meteor build build chdir={{ rana_prefix }}
    when: rana_sync.changed
    sudo_user: "{{ rana_user }}"

  - name: Unarchive bundle
    unarchive: src={{ rana_prefix }}/build/rana.tar.gz dest={{ rana_prefix }} copy=no
    when: rana_sync.changed
    sudo_user: "{{ rana_user }}"

  - name: Install npm modules
    command: npm install
    args:
      chdir: "{{ rana_prefix }}/bundle/programs/server"
    sudo_user: "{{ rana_user }}"

  - name: Install supervisord config
    template: src=ranad.conf.j2 dest=/etc/supervisor/conf.d/ranad.conf
    sudo: yes
    sudo_user: root
    notify: reload supervisor
    with_items:
      - rana
      
  - name: Restart postfix
    command: service postfix restart
    sudo: yes

  - name: Restart rana process
    supervisorctl: name="rana" state=restarted
    when: rana_sync.changed
    sudo: yes
