---

- name: Add ppa:chris-lea/node.js
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Install node with dependencies
  apt: name={{item}} state=installed
  with_items:
    - python-software-properties
    - python
    - g++
    - make
    - nodejs
