---

- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - supervisor

- name: Create rana group
  user: name={{ rana_group }}

- name: Create rana user
  user: name={{ rana_user }} group={{ rana_group }} shell=/bin/bash

- name: Create rana environment configuration
  template: src=config.j2 dest=/home/{{ rana_user }}/rana_config group={{ rana_group }} owner={{ rana_user }}

- name: Create github key
  copy: content="{{git_key}}" dest=~/.ssh/id_rsa mode="0700"
  sudo_user: "{{ rana_user }}"
